language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
install:
  - pip install flake8 pytest 
  - pip install . --no-cache-dir
before_script:
  - flake8 tindetheus/__init__.py
  - flake8 tindetheus/export_embeddings.py
  - flake8 tindetheus/image_processing.py
  - flake8 tindetheus/machine_learning.py
  - flake8 tindetheus/tinder_client.py
  - flake8 tindetheus/tindetheus_align.py
  - flake8 tindetheus/tindetheus.py
  - cd tests
script: pytest -p no:warnings tests.py